ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "style(pre-commit.ci): auto fixes [...]"
  autoupdate_commit_msg: "ci(pre-commit.ci): autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*\\.md"
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: [
            --disable=MD033, # no-inline-html
            --disable=MD036, # no-emphasis-as-heading
          ]

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
        entry: uv run ruff format --force-exclude
      - id: ruff-check
        name: ruff check
        language: system
        types_or: [python, pyi]
        require_serial: true
        entry: uv run ruff check --force-exclude
        args: [--output-format=full, --show-fixes, --exit-non-zero-on-fix]
      - id: mypy
        name: mypy
        language: system
        types_or: [python, pyi]
        require_serial: true
        entry: uv run mypy
      - id: pyright
        name: pyright
        language: system
        types_or: [python, pyi]
        require_serial: true
        entry: uv run pyright

  - repo: https://github.com/crate-ci/typos
    rev: v1.31.1
    hooks:
      - id: typos
        args: [--force-exclude] # omitting --write-changes
