# pyright: reportOverlappingOverload=false, reportIncompatibleMethodOverride=false, reportAttributeAccessIssue=false
import enum
import typing

from typing_extensions import Self

from pymmcore_gui._qt import QtCore, QtGui, QtWidgets
from pymmcore_gui._qt.QtCore import Signal

class AboutDialog(QtWidgets.QDialog):
    def __init__(self, /, parent: QtWidgets.QWidget | None = ...) -> None: ...
    def addSocialMediaLink(
        self, name: str, url: str, /, icon: QtGui.QIcon | QtGui.QPixmap = ...
    ) -> None: ...
    def setApplicationName(self, name: str, /) -> None: ...
    def setApplicationVersion(self, version: str, /) -> None: ...
    def setCopyright(self, copyright: str, /) -> None: ...
    def setDescription(self, description: str, /) -> None: ...
    def setIcon(self, icon: QtGui.QIcon | QtGui.QPixmap, /) -> None: ...
    def setLicense(self, license: str, /) -> None: ...
    def setWebsiteUrl(self, url: str, /) -> None: ...

class AbstractItemListWidget(QtWidgets.QWidget):
    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        currentIndex: int | None = ...,
        currentData: typing.Any | None = ...,
        itemCount: int | None = ...,
        iconSize: QtCore.QSize | None = ...,
        itemsShouldExpand: bool | None = ...,
    ) -> None: ...
    def actualRect(self, /) -> QtCore.QRect: ...
    def addItem(
        self,
        text: str,
        /,
        icon: QtGui.QIcon | QtGui.QPixmap = ...,
        badge: str = ...,
        itemData: typing.Any = ...,
    ) -> int: ...
    def badgeFont(self, /) -> QtGui.QFont: ...
    def changeEvent(self, e: QtCore.QEvent, /) -> None: ...
    def currentData(self, /) -> typing.Any: ...
    def currentDataChanged(self, /) -> None: ...
    def currentIndex(self, /) -> int: ...
    def currentIndexChanged(self, /) -> None: ...
    def drawBackground(self, p: QtGui.QPainter, /) -> None: ...
    def drawCurrentItemIndicator(self, p: QtGui.QPainter, /) -> None: ...
    def enterEvent(self, e: QtGui.QEnterEvent, /) -> None: ...
    def event(self, e: QtCore.QEvent, /) -> bool: ...
    def findItemIndex(self, itemData: typing.Any, /) -> int: ...
    def focusInEvent(self, e: QtGui.QFocusEvent, /) -> None: ...
    def getAnimatedCurrentItemRect(self, /) -> QtCore.QRect: ...
    def getBadgePadding(self, /) -> QtCore.QMargins: ...
    @typing.overload
    def getBgColor(self, /) -> QtGui.QColor: ...
    @typing.overload
    def getBgColor(self, theme: Theme, /) -> QtGui.QColor: ...
    @typing.overload
    def getBgColor(
        self, palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor, /
    ) -> QtGui.QColor: ...
    def getCurrentItemIndicatorColor(self, /) -> QtGui.QColor: ...
    def getCurrentItemRect(self, /) -> QtCore.QRect: ...
    def getFocusedItemRect(self, /) -> QtCore.QRect: ...
    def getItemBadge(self, index: int, /) -> str: ...
    @typing.overload
    def getItemBadgeBgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeBgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeFgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeFgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBgColor(self, mouse: MouseState, theme: Theme, /) -> QtGui.QColor: ...
    @typing.overload
    def getItemBgColor(
        self,
        mouse: MouseState,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    def getItemData(self, index: int, /) -> typing.Any: ...
    @typing.overload
    def getItemFgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemFgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    def getItemIcon(self, index: int, /) -> QtGui.QIcon: ...
    def getItemMinimumHeight(self, /) -> int: ...
    def getItemPadding(self, /) -> QtCore.QMargins: ...
    def getItemRadius(self, /) -> float: ...
    def getItemSpacing(self, /) -> int: ...
    def getItemText(self, index: int, /) -> str: ...
    def getPadding(self, /) -> QtCore.QMargins: ...
    def getRadius(self, /) -> float: ...
    def getSpacing(self, /) -> int: ...
    def hitTestItemRect(
        self,
        pos: QtCore.QPoint,
        itemRect: QtCore.QRect,
        leftPadding: int,
        rightPadding: int,
        /,
    ) -> bool: ...
    def iconSize(self, /) -> QtCore.QSize: ...
    def iconSizeChanged(self, /) -> None: ...
    def isItemEnabled(self, index: int, /) -> bool: ...
    def itemAtPos(self, pos: QtCore.QPoint, /) -> int: ...
    def itemCount(self, /) -> int: ...
    def itemCountChanged(self, /) -> None: ...
    def itemsShouldExpand(self, /) -> bool: ...
    def itemsShouldExpandChanged(self, /) -> None: ...
    def keyPressEvent(self, e: QtGui.QKeyEvent, /) -> None: ...
    def keyReleaseEvent(self, e: QtGui.QKeyEvent, /) -> None: ...
    def labelFont(self, /) -> QtGui.QFont: ...
    def leaveEvent(self, e: QtCore.QEvent, /) -> None: ...
    def mouseMoveEvent(self, e: QtGui.QMouseEvent, /) -> None: ...
    def mousePressEvent(self, e: QtGui.QMouseEvent, /) -> None: ...
    def mouseReleaseEvent(self, e: QtGui.QMouseEvent, /) -> None: ...
    def moveToNextItem(self, /) -> None: ...
    def moveToPreviousItem(self, /) -> None: ...
    def paintEvent(self, e: QtGui.QPaintEvent, /) -> None: ...
    def removeItem(self, index: int, /) -> None: ...
    def resizeEvent(self, e: QtGui.QResizeEvent, /) -> None: ...
    def setCurrentData(self, currentData: typing.Any, /) -> None: ...
    def setCurrentIndex(self, index: int, /) -> None: ...
    def setFocusedIndex(self, index: int, /) -> None: ...
    def setHoveredIndex(self, index: int, /, updateAnims: bool = ...) -> None: ...
    def setIconSize(self, size: QtCore.QSize, /) -> None: ...
    def setItemBadge(self, index: int, badge: str, /) -> None: ...
    def setItemData(self, index: int, text: typing.Any, /) -> None: ...
    def setItemEnabled(self, index: int, enabled: bool, /) -> None: ...
    def setItemIcon(self, index: int, icon: QtGui.QIcon | QtGui.QPixmap, /) -> None: ...
    def setItemText(self, index: int, text: str, /) -> None: ...
    def setItemsShouldExpand(self, expand: bool, /) -> None: ...
    def setPressedIndex(self, index: int, /, updateAnims: bool = ...) -> None: ...
    def shouldDrawItemBgForCurrent(self, /) -> bool: ...
    def showEvent(self, e: QtGui.QShowEvent, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...
    def updateCurrentIndexAnimation(self, /, immediate: bool = ...) -> None: ...
    def updateItemRects(self, /) -> None: ...
    def updateItemsAnimations(self, /) -> None: ...
    def updateItemsSizeHints(self, /) -> None: ...

class ActionButton(QtWidgets.QPushButton):
    def __init__(self, /, parent: QtWidgets.QWidget | None = ...) -> None: ...
    def setAction(self, action: QtGui.QAction, /) -> None: ...
    def updateFromAction(self, /) -> None: ...

class ActiveState(enum.IntEnum):
    NotActive = 0x0
    Active = 0x1

class AlternateState(enum.IntEnum):
    NotAlternate = 0x0
    Alternate = 0x1

class AutoIconColor(enum.IntEnum):
    None_ = 0x0
    ForegroundColor = 0x1
    TextColor = 0x2

class CheckState(enum.IntEnum):
    NotChecked = 0x0
    Checked = 0x1
    Indeterminate = 0x2

class ColorButton(QtWidgets.QAbstractButton):
    colorChanged: typing.ClassVar[Signal] = ...  # colorChanged()
    colorModeChanged: typing.ClassVar[Signal] = ...  # colorModeChanged()

    @typing.overload
    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        color: QtGui.QColor | None = ...,
        colorMode: ColorMode | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        color: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        mode: ColorMode,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        colorMode: ColorMode | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        color: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        colorMode: ColorMode | None = ...,
    ) -> None: ...
    def color(self, /) -> QtGui.QColor: ...
    def colorMode(self, /) -> ColorMode: ...
    def paintEvent(self, arg__1: QtGui.QPaintEvent, /) -> None: ...
    def setColor(
        self,
        color: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
    ) -> None: ...
    def setColorMode(self, mode: ColorMode, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...

class ColorEditor(QtWidgets.QWidget):
    colorChanged: typing.ClassVar[Signal] = ...  # colorChanged()
    colorModeChanged: typing.ClassVar[Signal] = ...  # colorModeChanged()

    @typing.overload
    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        color: QtGui.QColor | None = ...,
        colorMode: ColorMode | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        color: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        colorMode: ColorMode | None = ...,
    ) -> None: ...
    def color(self, /) -> QtGui.QColor: ...
    def colorMode(self, /) -> ColorMode: ...
    def setColor(
        self,
        color: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
    ) -> None: ...
    def setColorMode(self, mode: ColorMode, /) -> None: ...

class ColorMode(enum.IntEnum):
    RGB = 0x0
    RGBA = 0x1

class ColorRole(enum.IntEnum):
    Primary = 0x0
    Secondary = 0x1

class ColorizeMode(enum.IntEnum):
    Colorize = 0x0
    Tint = 0x1

class CommandLinkButton(QtWidgets.QCommandLinkButton):
    @typing.overload
    def __init__(
        self, text: str, description: str, /, parent: QtWidgets.QWidget | None = ...
    ) -> None: ...
    @typing.overload
    def __init__(
        self, text: str, /, parent: QtWidgets.QWidget | None = ...
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        icon: QtGui.QIcon | QtGui.QPixmap,
        text: str,
        description: str,
        /,
        parent: QtWidgets.QWidget | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(self, /, parent: QtWidgets.QWidget | None = ...) -> None: ...
    def hasHeightForWidth(self, /) -> bool: ...
    def heightForWidth(self, arg__1: int, /) -> int: ...
    def paintEvent(self, arg__1: QtGui.QPaintEvent, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...

class DefaultState(enum.IntEnum):
    NotDefault = 0x0
    Default = 0x1

class Expander(QtWidgets.QWidget):
    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        expanded: bool | None = ...,
        orientation: QtCore.Qt.Orientation | None = ...,
    ) -> None: ...
    def aboutToExpand(self, /) -> None: ...
    def aboutToShrink(self, /) -> None: ...
    def content(self, /) -> QtWidgets.QWidget: ...
    def contentChanged(self, /) -> None: ...
    def didExpand(self, /) -> None: ...
    def didShrink(self, /) -> None: ...
    def event(self, e: QtCore.QEvent, /) -> bool: ...
    def eventFilter(self, o: QtCore.QObject, e: QtCore.QEvent, /) -> bool: ...
    def expanded(self, /) -> bool: ...
    def expandedChanged(self, /) -> None: ...
    def orientation(self, /) -> QtCore.Qt.Orientation: ...
    def orientationChanged(self, /) -> None: ...
    def resizeEvent(self, e: QtGui.QResizeEvent, /) -> None: ...
    def setContent(self, content: QtWidgets.QWidget, /) -> None: ...
    def setExpanded(self, expanded: bool, /) -> None: ...
    def setOrientation(self, orientation: QtCore.Qt.Orientation, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...
    def toggleExpanded(self, /) -> None: ...

class FocusState(enum.IntEnum):
    NotFocused = 0x0
    Focused = 0x1

class IconWidget(QtWidgets.QWidget):
    @typing.overload
    def __init__(
        self,
        icon: QtGui.QIcon | QtGui.QPixmap,
        size: QtCore.QSize,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        iconSize: QtCore.QSize | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        icon: QtGui.QIcon | QtGui.QPixmap,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        iconSize: QtCore.QSize | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        icon: QtGui.QIcon | None = ...,
        iconSize: QtCore.QSize | None = ...,
    ) -> None: ...
    def icon(self, /) -> QtGui.QIcon: ...
    def iconChanged(self, /) -> None: ...
    def iconSize(self, /) -> QtCore.QSize: ...
    def iconSizeChanged(self, /) -> None: ...
    def paintEvent(self, e: QtGui.QPaintEvent, /) -> None: ...
    def setIcon(self, icon: QtGui.QIcon | QtGui.QPixmap, /) -> None: ...
    def setIconSize(self, iconSize: QtCore.QSize, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...

class Label(QtWidgets.QLabel):
    @typing.overload
    def __init__(
        self, text: str, /, role: TextRole = ..., parent: QtWidgets.QWidget | None = ...
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        text: str,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        role: TextRole | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self, /, parent: QtWidgets.QWidget | None = ..., *, role: TextRole | None = ...
    ) -> None: ...
    def event(self, e: QtCore.QEvent, /) -> bool: ...
    def eventFilter(self, o: QtCore.QObject, e: QtCore.QEvent, /) -> bool: ...
    def role(self, /) -> TextRole: ...
    def roleChanged(self, /) -> None: ...
    def setRole(self, role: TextRole, /) -> None: ...

class LineEdit(QtWidgets.QLineEdit):
    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        icon: QtGui.QIcon | None = ...,
        status: Status | None = ...,
    ) -> None: ...
    def event(self, e: QtCore.QEvent, /) -> bool: ...
    def icon(self, /) -> QtGui.QIcon: ...
    def iconChanged(self, /) -> None: ...
    def paintEvent(self, evt: QtGui.QPaintEvent, /) -> None: ...
    def setIcon(self, icon: QtGui.QIcon | QtGui.QPixmap, /) -> None: ...
    def setStatus(self, status: Status, /) -> None: ...
    def setUseMonoSpaceFont(self, useMonoSpaceFont: bool, /) -> None: ...
    def status(self, /) -> Status: ...
    def statusChanged(self, /) -> None: ...
    def useMonoSpaceFont(self, /) -> bool: ...

class LoadingSpinner(QtWidgets.QWidget):
    def __init__(
        self, /, parent: QtWidgets.QWidget | None = ..., *, spinning: bool | None = ...
    ) -> None: ...
    def hideEvent(self, evt: QtGui.QHideEvent, /) -> None: ...
    def minimumSizeHint(self, /) -> QtCore.QSize: ...
    def paintEvent(self, evt: QtGui.QPaintEvent, /) -> None: ...
    def setSpinning(self, arg__1: bool, /) -> None: ...
    def showEvent(self, evt: QtGui.QShowEvent, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...
    def spinning(self, /) -> bool: ...
    def spinningChanged(self, /) -> None: ...
    def timerEvent(self, evt: QtCore.QTimerEvent, /) -> None: ...

class Menu(QtWidgets.QMenu):
    def __init__(self, /) -> None: ...
    def updateEnabled(self, /) -> None: ...
    def updateProps(self, /) -> None: ...
    def updateVisible(self, /) -> None: ...

class MouseState(enum.IntEnum):
    Transparent = 0x0
    Normal = 0x1
    Hovered = 0x2
    Pressed = 0x3
    Disabled = 0x4

class NavigationBar(AbstractItemListWidget):
    def __init__(self, /) -> None: ...
    def drawCurrentItemIndicator(self, p: QtGui.QPainter, /) -> None: ...
    @typing.overload
    def getBgColor(self, /) -> QtGui.QColor: ...
    @typing.overload
    def getBgColor(self, theme: Theme, /) -> QtGui.QColor: ...
    @typing.overload
    def getBgColor(
        self, palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeBgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeBgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeFgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeFgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBgColor(self, mouse: MouseState, theme: Theme, /) -> QtGui.QColor: ...
    @typing.overload
    def getItemBgColor(
        self,
        mouse: MouseState,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemFgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemFgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    def getItemMinimumHeight(self, /) -> int: ...
    def getItemPadding(self, /) -> QtCore.QMargins: ...
    def getItemRadius(self, /) -> float: ...
    def getPadding(self, /) -> QtCore.QMargins: ...
    def getSpacing(self, /) -> int: ...
    def labelFont(self, /) -> QtGui.QFont: ...

class NotificationBadge(QtWidgets.QWidget):
    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        text: str | None = ...,
        foregroundColor: QtGui.QColor | None = ...,
        backgroundColor: QtGui.QColor | None = ...,
        relativePosition: QtCore.QPoint | None = ...,
    ) -> None: ...
    def backgroundColor(self, /) -> QtGui.QColor: ...
    def backgroundColorChanged(self, /) -> None: ...
    def event(self, evt: QtCore.QEvent, /) -> bool: ...
    def eventFilter(self, obj: QtCore.QObject, evt: QtCore.QEvent, /) -> bool: ...
    def foregroundColor(self, /) -> QtGui.QColor: ...
    def foregroundColorChanged(self, /) -> None: ...
    def minimumSizeHint(self, /) -> QtCore.QSize: ...
    def padding(self, /) -> QtCore.QMargins: ...
    def paddingChanged(self, /) -> None: ...
    def paintEvent(self, evt: QtGui.QPaintEvent, /) -> None: ...
    def relativePosition(self, /) -> QtCore.QPoint: ...
    def relativePositionChanged(self, /) -> None: ...
    def setBackgroundColor(
        self,
        arg__1: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
    ) -> None: ...
    def setForegroundColor(
        self,
        arg__1: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
    ) -> None: ...
    def setPadding(self, arg__1: QtCore.QMargins, /) -> None: ...
    @typing.overload
    def setRelativePosition(self, arg__1: QtCore.QPoint, /) -> None: ...
    @typing.overload
    def setRelativePosition(self, x: int, y: int, /) -> None: ...
    def setText(self, arg__1: str, /) -> None: ...
    def setWidget(self, widget: QtWidgets.QWidget, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...
    def text(self, /) -> str: ...
    def textChanged(self, /) -> None: ...
    def widget(self, /) -> QtWidgets.QWidget: ...

class PlainTextEdit(QtWidgets.QPlainTextEdit):
    def __init__(
        self, /, parent: QtWidgets.QWidget | None = ..., *, status: Status | None = ...
    ) -> None: ...
    def minimumSizeHint(self, /) -> QtCore.QSize: ...
    def setStatus(self, status: Status, /) -> None: ...
    def setUseMonoSpaceFont(self, useMonoSpaceFont: bool, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...
    def status(self, /) -> Status: ...
    def statusChanged(self, /) -> None: ...
    def useMonoSpaceFont(self, /) -> bool: ...

class Popover(QtWidgets.QWidget):
    aboutToClose: typing.ClassVar[Signal] = ...  # aboutToClose()
    aboutToOpen: typing.ClassVar[Signal] = ...  # aboutToOpen()
    anchorWidgetChanged: typing.ClassVar[Signal] = ...  # anchorWidgetChanged()
    backgroundColorChanged: typing.ClassVar[Signal] = ...  # backgroundColorChanged()
    borderColorChanged: typing.ClassVar[Signal] = ...  # borderColorChanged()
    borderWidthChanged: typing.ClassVar[Signal] = ...  # borderWidthChanged()
    canBeOverAnchorChanged: typing.ClassVar[Signal] = ...  # canBeOverAnchorChanged()
    closed: typing.ClassVar[Signal] = ...  # closed()
    contentMaskEnabledChanged: typing.ClassVar[
        Signal
    ] = ...  # contentMaskEnabledChanged()
    contentWidgetChanged: typing.ClassVar[Signal] = ...  # contentWidgetChanged()
    deleteContentAfterClosingChanged: typing.ClassVar[
        Signal
    ] = ...  # deleteContentAfterClosingChanged()
    dropShadowColorChanged: typing.ClassVar[Signal] = ...  # dropShadowColorChanged()
    dropShadowOffsetChanged: typing.ClassVar[Signal] = ...  # dropShadowOffsetChanged()
    dropShadowRadiusChanged: typing.ClassVar[Signal] = ...  # dropShadowRadiusChanged()
    horizontalSpacingChanged: typing.ClassVar[
        Signal
    ] = ...  # horizontalSpacingChanged()
    manualPositionRequested: typing.ClassVar[Signal] = ...  # manualPositionRequested()
    manualPositioningChanged: typing.ClassVar[
        Signal
    ] = ...  # manualPositioningChanged()
    opened: typing.ClassVar[Signal] = ...  # opened()
    openedChanged: typing.ClassVar[Signal] = ...  # openedChanged()
    paddingChanged: typing.ClassVar[Signal] = ...  # paddingChanged()
    preferredAlignmentChanged: typing.ClassVar[
        Signal
    ] = ...  # preferredAlignmentChanged()
    preferredPositionChanged: typing.ClassVar[
        Signal
    ] = ...  # preferredPositionChanged()
    pressed: typing.ClassVar[Signal] = ...  # pressed()
    radiusChanged: typing.ClassVar[Signal] = ...  # radiusChanged()
    released: typing.ClassVar[Signal] = ...  # released()
    screenPaddingChanged: typing.ClassVar[Signal] = ...  # screenPaddingChanged()
    verticalSpacingChanged: typing.ClassVar[Signal] = ...  # verticalSpacingChanged()

    class Alignment(enum.IntEnum):
        Begin = 0x0
        Center = 0x1
        End = 0x2

    class Position(enum.IntEnum):
        Left = 0x0
        Top = 0x1
        Right = 0x2
        Bottom = 0x3

    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        manualPositioning: bool | None = ...,
        preferredPosition: Popover.Position | None = ...,
        preferredAlignment: Popover.Alignment | None = ...,
        isOpened: bool | None = ...,
        padding: QtCore.QMargins | None = ...,
        horizontalSpacing: int | None = ...,
        verticalSpacing: int | None = ...,
        screenPadding: QtCore.QMargins | None = ...,
        dropShadowColor: QtGui.QColor | None = ...,
        radius: float | None = ...,
        borderWidth: float | None = ...,
        dropShadowRadius: float | None = ...,
        dropShadowOffset: QtCore.QPointF | None = ...,
        canBeOverAnchor: bool | None = ...,
        deleteContentAfterClosing: bool | None = ...,
        contentMaskEnabled: bool | None = ...,
        backgroundColor: QtGui.QColor | None = ...,
        borderColor: QtGui.QColor | None = ...,
    ) -> None: ...
    def anchorWidget(self, /) -> QtWidgets.QWidget: ...
    def backgroundColor(self, /) -> QtGui.QColor: ...
    def borderColor(self, /) -> QtGui.QColor: ...
    def borderWidth(self, /) -> float: ...
    def canBeOverAnchor(self, /) -> bool: ...
    def closePopover(self, /) -> None: ...
    def contentMaskEnabled(self, /) -> bool: ...
    def contentWidget(self, /) -> QtWidgets.QWidget: ...
    def deleteContentAfterClosing(self, /) -> bool: ...
    def dropShadowColor(self, /) -> QtGui.QColor: ...
    def dropShadowOffset(self, /) -> QtCore.QPointF: ...
    def dropShadowRadius(self, /) -> float: ...
    def hideEvent(self, e: QtGui.QHideEvent, /) -> None: ...
    def horizontalSpacing(self, /) -> int: ...
    def isClosed(self, /) -> bool: ...
    def isOpened(self, /) -> bool: ...
    def manualPositioning(self, /) -> bool: ...
    def mousePressEvent(self, e: QtGui.QMouseEvent, /) -> None: ...
    def mouseReleaseEvent(self, e: QtGui.QMouseEvent, /) -> None: ...
    def openPopover(self, /) -> None: ...
    def padding(self, /) -> QtCore.QMargins: ...
    def paintEvent(self, e: QtGui.QPaintEvent, /) -> None: ...
    def popoverFrameSize(self, /) -> QtCore.QSize: ...
    def preferredAlignment(self, /) -> Popover.Alignment: ...
    def preferredPosition(self, /) -> Popover.Position: ...
    def radius(self, /) -> float: ...
    def screenPadding(self, /) -> QtCore.QMargins: ...
    def setAnchorWidget(self, widget: QtWidgets.QWidget, /) -> None: ...
    def setBackgroundColor(
        self,
        arg__1: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
    ) -> None: ...
    def setBorderColor(
        self,
        arg__1: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
    ) -> None: ...
    def setBorderWidth(self, width: float, /) -> None: ...
    def setCanBeOverAnchor(self, value: bool, /) -> None: ...
    def setClosed(self, closed: bool, /) -> None: ...
    def setContentMaskEnabled(self, arg__1: bool, /) -> None: ...
    def setContentWidget(self, widget: QtWidgets.QWidget, /) -> None: ...
    def setDeleteContentAfterClosing(self, arg__1: bool, /) -> None: ...
    def setDropShadowColor(
        self,
        arg__1: QtGui.QColor
        | str
        | QtGui.QRgba64
        | typing.Any
        | QtCore.Qt.GlobalColor
        | int,
        /,
    ) -> None: ...
    def setDropShadowOffset(
        self, offset: QtCore.QPointF | QtCore.QPoint, /
    ) -> None: ...
    def setDropShadowRadius(self, radius: float, /) -> None: ...
    def setHorizontalSpacing(self, spacing: int, /) -> None: ...
    def setManualPositioning(self, manual: bool, /) -> None: ...
    def setOpened(self, opened: bool, /) -> None: ...
    def setPadding(self, padding: QtCore.QMargins, /) -> None: ...
    def setPreferredAlignment(self, alignment: Popover.Alignment, /) -> None: ...
    def setPreferredPosition(self, position: Popover.Position, /) -> None: ...
    def setRadius(self, radius: float, /) -> None: ...
    def setScreenPadding(self, padding: QtCore.QMargins, /) -> None: ...
    def setVerticalSpacing(self, spacing: int, /) -> None: ...
    def showEvent(self, e: QtGui.QShowEvent, /) -> None: ...
    def togglePopover(self, /) -> None: ...
    def verticalSpacing(self, /) -> int: ...

class PopoverButton(QtWidgets.QPushButton):
    popoverContentWidgetChanged: typing.ClassVar[
        Signal
    ] = ...  # popoverContentWidgetChanged()
    popoverOpenedChanged: typing.ClassVar[Signal] = ...  # popoverOpenedChanged(bool)

    @typing.overload
    def __init__(
        self,
        text: str,
        icon: QtGui.QIcon | QtGui.QPixmap,
        /,
        parent: QtWidgets.QWidget | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self, text: str, /, parent: QtWidgets.QWidget | None = ...
    ) -> None: ...
    @typing.overload
    def __init__(self, /, parent: QtWidgets.QWidget | None = ...) -> None: ...
    def paintEvent(self, e: QtGui.QPaintEvent, /) -> None: ...
    def popover(self, /) -> Popover: ...
    def popoverContentWidget(self, /) -> QtWidgets.QWidget: ...
    def setPopoverContentWidget(self, widget: QtWidgets.QWidget, /) -> None: ...
    def setPopoverOpened(self, opened: bool, /) -> None: ...

class QIntList: ...

class QlementineStyle(QtWidgets.QCommonStyle):
    class ContentsTypeExt(enum.IntEnum):
        CT_CommandButton = 0x0

    class ControlElementExt(enum.IntEnum):
        CE_CommandButtonLabel = 0x0
        CE_CommandButton = 0x1

    class PixelMetricExt(enum.IntEnum):
        PM_MediumIconSize = 0x0

    class PrimitiveElementExt(enum.IntEnum):
        PE_CommandButtonPanel = 0x0
        PE_CommandButtonLabel = 0x1

    class StandardPixmapExt(enum.IntEnum):
        SP_Check = 0x0
        SP_Calendar = 0x1

    def __init__(
        self,
        /,
        parent: QtCore.QObject | None = ...,
        *,
        animationsEnabled: bool | None = ...,
    ) -> None: ...
    def animationsEnabled(self, /) -> bool: ...
    def animationsEnabledChanged(self, /) -> None: ...
    def autoIconColor(self, /) -> AutoIconColor: ...
    def buttonBackgroundColor(
        self, mouse: MouseState, role: ColorRole, /, w: QtWidgets.QWidget | None = ...
    ) -> QtGui.QColor: ...
    def buttonForegroundColor(
        self, mouse: MouseState, role: ColorRole, /, w: QtWidgets.QWidget | None = ...
    ) -> QtGui.QColor: ...
    def cellItemFocusBorderColor(
        self, focus: FocusState, selected: SelectionState, active: ActiveState, /
    ) -> QtGui.QColor: ...
    def checkButtonBackgroundColor(
        self, mouse: MouseState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def checkButtonBorderColor(
        self, mouse: MouseState, focus: FocusState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def checkButtonForegroundColor(
        self, mouse: MouseState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def color(self, mouse: MouseState, role: ColorRole, /) -> QtGui.QColor: ...
    def colorForTextRole(
        self, role: TextRole, mouse: MouseState, /
    ) -> QtGui.QColor: ...
    def comboBoxBackgroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def comboBoxForegroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def comboBoxTextColor(
        self, mouse: MouseState, status: Status, /, w: QtWidgets.QWidget | None = ...
    ) -> QtGui.QColor: ...
    def commandButtonBackgroundColor(
        self, mouse: MouseState, role: ColorRole, /
    ) -> QtGui.QColor: ...
    def commandButtonDescriptionColor(
        self, mouse: MouseState, role: ColorRole, /
    ) -> QtGui.QColor: ...
    def commandButtonIconColor(
        self, mouse: MouseState, role: ColorRole, /
    ) -> QtGui.QColor: ...
    def commandButtonTextColor(
        self, mouse: MouseState, role: ColorRole, /
    ) -> QtGui.QColor: ...
    def dialBackgroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def dialGrooveColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def dialHandleColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def dialMarkColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def dialTickColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def dialValueColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def drawControlExt(
        self,
        ce: QlementineStyle.ControlElementExt,
        opt: QtWidgets.QStyleOption,
        p: QtGui.QPainter,
        /,
        w: QtWidgets.QWidget | None = ...,
    ) -> None: ...
    def drawPrimitiveExt(
        self,
        pe: QlementineStyle.PrimitiveElementExt,
        opt: QtWidgets.QStyleOption,
        p: QtGui.QPainter,
        /,
        w: QtWidgets.QWidget | None = ...,
    ) -> None: ...
    def focusBorderColor(self, status: Status, /) -> QtGui.QColor: ...
    def fontForTextRole(self, role: TextRole, /) -> QtGui.QFont: ...
    def frameBackgroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def frameBorderColor(self, /) -> QtGui.QColor: ...
    def getScrollBarThickness(self, mouse: MouseState, /) -> int: ...
    def groupBoxBackgroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def groupBoxBorderColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def groupBoxTitleColor(
        self, mouse: MouseState, /, w: QtWidgets.QWidget | None = ...
    ) -> QtGui.QColor: ...
    def iconForegroundColor(
        self, mouse: MouseState, role: ColorRole, /
    ) -> QtGui.QColor: ...
    def labelCaptionForegroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def labelForegroundColor(
        self, mouse: MouseState, /, w: QtWidgets.QWidget | None = ...
    ) -> QtGui.QColor: ...
    def listItemAutoIconColor(
        self,
        mouse: MouseState,
        selected: SelectionState,
        focus: FocusState,
        active: ActiveState,
        index: QtCore.QModelIndex | QtCore.QPersistentModelIndex,
        /,
        widget: QtWidgets.QWidget | None = ...,
    ) -> AutoIconColor: ...
    def listItemBackgroundColor(
        self,
        mouse: MouseState,
        selected: SelectionState,
        focus: FocusState,
        active: ActiveState,
        index: QtCore.QModelIndex | QtCore.QPersistentModelIndex,
        /,
        widget: QtWidgets.QWidget | None = ...,
    ) -> QtGui.QColor: ...
    def listItemCaptionForegroundColor(
        self,
        mouse: MouseState,
        selected: SelectionState,
        focus: FocusState,
        active: ActiveState,
        /,
    ) -> QtGui.QColor: ...
    def listItemCheckButtonBackgroundColor(
        self,
        mouse: MouseState,
        checked: CheckState,
        selected: SelectionState,
        active: ActiveState,
        /,
    ) -> QtGui.QColor: ...
    def listItemCheckButtonBorderColor(
        self,
        mouse: MouseState,
        checked: CheckState,
        selected: SelectionState,
        active: ActiveState,
        /,
    ) -> QtGui.QColor: ...
    def listItemCheckButtonForegroundColor(
        self,
        mouse: MouseState,
        checked: CheckState,
        selected: SelectionState,
        active: ActiveState,
        /,
    ) -> QtGui.QColor: ...
    def listItemForegroundColor(
        self,
        mouse: MouseState,
        selected: SelectionState,
        focus: FocusState,
        active: ActiveState,
        /,
    ) -> QtGui.QColor: ...
    def listItemRowBackgroundColor(
        self, mouse: MouseState, alternate: AlternateState, /
    ) -> QtGui.QColor: ...
    def makeThemedIcon(
        self, svgPath: str, /, size: QtCore.QSize = ..., role: ColorRole = ...
    ) -> QtGui.QIcon: ...
    def makeThemedIconFromName(
        self, name: str, /, size: QtCore.QSize = ..., role: ColorRole = ...
    ) -> QtGui.QIcon: ...
    def menuBackgroundColor(self, /) -> QtGui.QColor: ...
    def menuBarBackgroundColor(self, /) -> QtGui.QColor: ...
    def menuBarBorderColor(self, /) -> QtGui.QColor: ...
    def menuBarItemBackgroundColor(
        self, mouse: MouseState, selected: SelectionState, /
    ) -> QtGui.QColor: ...
    def menuBarItemForegroundColor(
        self, mouse: MouseState, selected: SelectionState, /
    ) -> QtGui.QColor: ...
    def menuBorderColor(self, /) -> QtGui.QColor: ...
    def menuItemBackgroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def menuItemForegroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def menuItemSecondaryForegroundColor(
        self, mouse: MouseState, /
    ) -> QtGui.QColor: ...
    def menuSeparatorColor(self, /) -> QtGui.QColor: ...
    def paletteForTextRole(self, role: TextRole, /) -> QtGui.QPalette: ...
    def pixelMetricExt(
        self,
        m: QlementineStyle.PixelMetricExt,
        /,
        opt: QtWidgets.QStyleOption | None = ...,
        w: QtWidgets.QWidget | None = ...,
    ) -> int: ...
    def pixelSizeForTextRole(self, role: TextRole, /) -> int: ...
    def progressBarGrooveColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def progressBarValueColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def radioButtonBackgroundColor(
        self, mouse: MouseState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def radioButtonBorderColor(
        self, mouse: MouseState, focus: FocusState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def radioButtonForegroundColor(
        self, mouse: MouseState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def scrollBarGrooveColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def scrollBarHandleColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def separatorColor(self, /) -> QtGui.QColor: ...
    def setAnimationsEnabled(self, enabled: bool, /) -> None: ...
    def setAutoIconColor(self, autoIconColor: AutoIconColor, /) -> None: ...
    def setTheme(self, theme: Theme, /) -> None: ...
    def setThemeJsonPath(self, jsonPath: str, /) -> None: ...
    def sizeFromContentsExt(
        self,
        ct: QlementineStyle.ContentsTypeExt,
        opt: QtWidgets.QStyleOption,
        s: QtCore.QSize,
        /,
        w: QtWidgets.QWidget | None = ...,
    ) -> QtCore.QSize: ...
    def sliderGrooveColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def sliderHandleColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def sliderTickColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def sliderValueColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def spinBoxBackgroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def spinBoxBorderColor(
        self, mouse: MouseState, focus: FocusState, /
    ) -> QtGui.QColor: ...
    def spinBoxButtonBackgroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def spinBoxButtonForegroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def splitterColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def standardIconExt(
        self,
        sp: QlementineStyle.StandardPixmapExt,
        /,
        opt: QtWidgets.QStyleOption | None = ...,
        w: QtWidgets.QWidget | None = ...,
    ) -> QtGui.QIcon: ...
    def statusBarBackgroundColor(self, /) -> QtGui.QColor: ...
    def statusBarBorderColor(self, /) -> QtGui.QColor: ...
    def statusBarSeparatorColor(self, /) -> QtGui.QColor: ...
    def statusColor(self, status: Status, mouse: MouseState, /) -> QtGui.QColor: ...
    def statusColorForeground(
        self, status: Status, mouse: MouseState, /
    ) -> QtGui.QColor: ...
    def switchGrooveBorderColor(
        self, mouse: MouseState, focus: FocusState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def switchGrooveColor(
        self, mouse: MouseState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def switchHandleColor(
        self, mouse: MouseState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def tabBackgroundColor(
        self, mouse: MouseState, selected: SelectionState, /
    ) -> QtGui.QColor: ...
    def tabBarBackgroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def tabBarBottomShadowColor(self, /) -> QtGui.QColor: ...
    def tabBarScrollButtonBackgroundColor(
        self, mouse: MouseState, /
    ) -> QtGui.QColor: ...
    def tabBarShadowColor(self, /) -> QtGui.QColor: ...
    def tabCloseButtonBackgroundColor(
        self, mouse: MouseState, selected: SelectionState, /
    ) -> QtGui.QColor: ...
    def tabCloseButtonForegroundColor(
        self, mouse: MouseState, selected: SelectionState, /
    ) -> QtGui.QColor: ...
    def tabForegroundColor(
        self, mouse: MouseState, selected: SelectionState, /
    ) -> QtGui.QColor: ...
    def tabTextColor(
        self,
        mouse: MouseState,
        selected: SelectionState,
        optTab: QtWidgets.QStyleOptionTab,
        /,
        w: QtWidgets.QWidget | None = ...,
    ) -> QtGui.QColor: ...
    def tableHeaderBgColor(
        self, mouse: MouseState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def tableHeaderFgColor(
        self, mouse: MouseState, checked: CheckState, /
    ) -> QtGui.QColor: ...
    def tableLineColor(self, /) -> QtGui.QColor: ...
    def textFieldBackgroundColor(
        self, mouse: MouseState, status: Status, /
    ) -> QtGui.QColor: ...
    def textFieldBorderColor(
        self, mouse: MouseState, focus: FocusState, status: Status, /
    ) -> QtGui.QColor: ...
    def textFieldForegroundColor(self, mouse: MouseState, /) -> QtGui.QColor: ...
    def theme(self, /) -> Theme: ...
    def themeChanged(self, /) -> None: ...
    def toolBarBackgroundColor(self, /) -> QtGui.QColor: ...
    def toolBarBorderColor(self, /) -> QtGui.QColor: ...
    def toolBarSeparatorColor(self, /) -> QtGui.QColor: ...
    def toolButtonBackgroundColor(
        self, mouse: MouseState, role: ColorRole, /
    ) -> QtGui.QColor: ...
    def toolButtonForegroundColor(
        self, mouse: MouseState, role: ColorRole, /
    ) -> QtGui.QColor: ...
    def toolButtonSeparatorColor(
        self, mouse: MouseState, role: ColorRole, /
    ) -> QtGui.QColor: ...
    def toolTipBackgroundColor(self, /) -> QtGui.QColor: ...
    def toolTipBorderColor(self, /) -> QtGui.QColor: ...
    def toolTipForegroundColor(self, /) -> QtGui.QColor: ...
    def triggerCompleteRepaint(self, /) -> None: ...

class RadiusesF:
    bottomLeft = ...  # type: float
    bottomRight = ...  # type: float
    topLeft = ...  # type: float
    topRight = ...  # type: float

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, RadiusesF: RadiusesF, /) -> None: ...
    @typing.overload
    def __init__(self, radius: int, /) -> None: ...
    @typing.overload
    def __init__(self, left: int, right: int, /) -> None: ...
    @typing.overload
    def __init__(
        self, topLeft: int, topRight: int, bottomRight: int, bottomLeft: int, /
    ) -> None: ...
    @typing.overload
    def __init__(self, radius: float, /) -> None: ...
    @typing.overload
    def __init__(self, left: float, right: float, /) -> None: ...
    @typing.overload
    def __init__(
        self, topLeft: float, topRight: float, bottomRight: float, bottomLeft: float, /
    ) -> None: ...
    def __add__(self, rhs: float, /) -> RadiusesF: ...
    def __copy__(self, /) -> Self: ...
    @typing.overload
    def __eq__(self, rhs: RadiusesF, /) -> bool: ...
    @typing.overload
    def __eq__(self, rhs: float, /) -> bool: ...
    def __ge__(self, rhs: float, /) -> bool: ...
    def __gt__(self, rhs: float, /) -> bool: ...
    def __le__(self, rhs: float, /) -> bool: ...
    def __lt__(self, rhs: float, /) -> bool: ...
    @typing.overload
    def __ne__(self, rhs: RadiusesF, /) -> bool: ...
    @typing.overload
    def __ne__(self, rhs: float, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __sub__(self, rhs: float, /) -> RadiusesF: ...
    def hasDifferentRadius(self, /) -> bool: ...
    def hasSameRadius(self, /) -> bool: ...

class RoundedFocusFrame(QtWidgets.QFocusFrame):
    def __init__(self, /, *, radiuses: RadiusesF | None = ...) -> None: ...
    def radiuses(self, /) -> RadiusesF: ...
    def radiusesChanged(self, /) -> None: ...
    def setRadiuses(self, arg__1: RadiusesF, /) -> None: ...

class SegmentedControl(AbstractItemListWidget):
    def __init__(self, /) -> None: ...
    @typing.overload
    def getBgColor(self, /) -> QtGui.QColor: ...
    @typing.overload
    def getBgColor(self, theme: Theme, /) -> QtGui.QColor: ...
    @typing.overload
    def getBgColor(
        self, palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeBgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeBgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeFgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBadgeFgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemBgColor(self, mouse: MouseState, theme: Theme, /) -> QtGui.QColor: ...
    @typing.overload
    def getItemBgColor(
        self,
        mouse: MouseState,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemFgColor(
        self, mouse: MouseState, selected: bool, theme: Theme, /
    ) -> QtGui.QColor: ...
    @typing.overload
    def getItemFgColor(
        self,
        mouse: MouseState,
        selected: bool,
        palette: QtGui.QPalette | QtCore.Qt.GlobalColor | QtGui.QColor,
        /,
    ) -> QtGui.QColor: ...

class SelectionState(enum.IntEnum):
    NotSelected = 0x0
    Selected = 0x1

class Status(enum.IntEnum):
    Default = 0x0
    Info = 0x1
    Success = 0x2
    Warning = 0x3
    Error = 0x4

class StatusBadge(enum.IntEnum):
    Success = 0x0
    Info = 0x1
    Warning = 0x2
    Error = 0x3

class StatusBadgeSize(enum.IntEnum):
    Small = 0x0
    Medium = 0x1

class StatusBadgeWidget(QtWidgets.QWidget):
    @typing.overload
    def __init__(
        self,
        badge: StatusBadge,
        badgeSize: StatusBadgeSize,
        /,
        parent: QtWidgets.QWidget | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self, badge: StatusBadge, /, parent: QtWidgets.QWidget | None = ...
    ) -> None: ...
    @typing.overload
    def __init__(self, /, parent: QtWidgets.QWidget | None = ...) -> None: ...
    def badge(self, /) -> StatusBadge: ...
    def badgeChanged(self, /) -> None: ...
    def badgeSize(self, /) -> StatusBadgeSize: ...
    def badgeSizeChanged(self, /) -> None: ...
    def paintEvent(self, e: QtGui.QPaintEvent, /) -> None: ...
    def setBadge(self, badge: StatusBadge, /) -> None: ...
    def setBadgeSize(self, size: StatusBadgeSize, /) -> None: ...
    def sizeHint(self, /) -> QtCore.QSize: ...

class Switch(QtWidgets.QAbstractButton):
    checkStateChanged: typing.ClassVar[Signal] = ...  # checkStateChanged(int)
    showAccessibilitySymbolsChanged: typing.ClassVar[
        Signal
    ] = ...  # showAccessibilitySymbolsChanged(bool)
    tristateChanged: typing.ClassVar[Signal] = ...  # tristateChanged(bool)

    def __init__(
        self,
        /,
        parent: QtWidgets.QWidget | None = ...,
        *,
        tristate: bool | None = ...,
        showAccessibilitySymbols: bool | None = ...,
    ) -> None: ...
    def changeEvent(self, e: QtCore.QEvent, /) -> None: ...
    def checkState(self, /) -> QtCore.Qt.CheckState: ...
    def checkStateSet(self, /) -> None: ...
    def enterEvent(self, e: QtGui.QEnterEvent, /) -> None: ...
    def focusInEvent(self, e: QtGui.QFocusEvent, /) -> None: ...
    def focusOutEvent(self, e: QtGui.QFocusEvent, /) -> None: ...
    def isTristate(self, /) -> bool: ...
    def leaveEvent(self, e: QtCore.QEvent, /) -> None: ...
    def nextCheckState(self, /) -> None: ...
    def paintEvent(self, e: QtGui.QPaintEvent, /) -> None: ...
    def setCheckState(self, state: QtCore.Qt.CheckState, /) -> None: ...
    def setShowAccessibilitySymbols(
        self, showAccessibilitySymbols: bool, /
    ) -> None: ...
    def setTristate(self, arg__1: bool, /) -> None: ...
    def showAccessibilitySymbols(self, /) -> bool: ...
    def sizeHint(self, /) -> QtCore.QSize: ...

class TextRole(enum.IntEnum):
    Caption = -1
    Default = 0x0
    H1 = 0x1
    H2 = 0x2
    H3 = 0x3
    H4 = 0x4
    H5 = 0x5

class Theme:
    animationDuration = ...  # type: int
    backgroundColorMain1 = ...  # type: QtGui.QColor
    backgroundColorMain2 = ...  # type: QtGui.QColor
    backgroundColorMain3 = ...  # type: QtGui.QColor
    backgroundColorMain4 = ...  # type: QtGui.QColor
    backgroundColorMainTransparent = ...  # type: QtGui.QColor
    backgroundColorTabBar = ...  # type: QtGui.QColor
    backgroundColorWorkspace = ...  # type: QtGui.QColor
    borderColor = ...  # type: QtGui.QColor
    borderColorDisabled = ...  # type: QtGui.QColor
    borderColorHovered = ...  # type: QtGui.QColor
    borderColorPressed = ...  # type: QtGui.QColor
    borderColorTransparent = ...  # type: QtGui.QColor
    borderRadius = ...  # type: float
    borderWidth = ...  # type: int
    checkBoxBorderRadius = ...  # type: float
    controlDefaultWidth = ...  # type: int
    controlHeightLarge = ...  # type: int
    controlHeightMedium = ...  # type: int
    controlHeightSmall = ...  # type: int
    dialGrooveThickness = ...  # type: int
    dialMarkLength = ...  # type: int
    dialMarkThickness = ...  # type: int
    dialTickLength = ...  # type: int
    dialTickSpacing = ...  # type: int
    focusAnimationDuration = ...  # type: int
    focusBorderWidth = ...  # type: int
    focusColor = ...  # type: QtGui.QColor
    fontBold = ...  # type: QtGui.QFont
    fontCaption = ...  # type: QtGui.QFont
    fontH1 = ...  # type: QtGui.QFont
    fontH2 = ...  # type: QtGui.QFont
    fontH3 = ...  # type: QtGui.QFont
    fontH4 = ...  # type: QtGui.QFont
    fontH5 = ...  # type: QtGui.QFont
    fontMonospace = ...  # type: QtGui.QFont
    fontRegular = ...  # type: QtGui.QFont
    fontSize = ...  # type: int
    fontSizeH1 = ...  # type: int
    fontSizeH2 = ...  # type: int
    fontSizeH3 = ...  # type: int
    fontSizeH4 = ...  # type: int
    fontSizeH5 = ...  # type: int
    fontSizeMonospace = ...  # type: int
    fontSizeS1 = ...  # type: int
    iconSize = ...  # type: QtCore.QSize
    iconSizeExtraSmall = ...  # type: QtCore.QSize
    iconSizeLarge = ...  # type: QtCore.QSize
    iconSizeMedium = ...  # type: QtCore.QSize
    menuBarItemBorderRadius = ...  # type: float
    menuItemBorderRadius = ...  # type: float
    meta = ...  # type: ThemeMeta
    neutralColor = ...  # type: QtGui.QColor
    neutralColorDisabled = ...  # type: QtGui.QColor
    neutralColorHovered = ...  # type: QtGui.QColor
    neutralColorPressed = ...  # type: QtGui.QColor
    neutralColorTransparent = ...  # type: QtGui.QColor
    palette = ...  # type: QtGui.QPalette
    primaryAlternativeColor = ...  # type: QtGui.QColor
    primaryAlternativeColorDisabled = ...  # type: QtGui.QColor
    primaryAlternativeColorHovered = ...  # type: QtGui.QColor
    primaryAlternativeColorPressed = ...  # type: QtGui.QColor
    primaryAlternativeColorTransparent = ...  # type: QtGui.QColor
    primaryColor = ...  # type: QtGui.QColor
    primaryColorDisabled = ...  # type: QtGui.QColor
    primaryColorForeground = ...  # type: QtGui.QColor
    primaryColorForegroundDisabled = ...  # type: QtGui.QColor
    primaryColorForegroundHovered = ...  # type: QtGui.QColor
    primaryColorForegroundPressed = ...  # type: QtGui.QColor
    primaryColorForegroundTransparent = ...  # type: QtGui.QColor
    primaryColorHovered = ...  # type: QtGui.QColor
    primaryColorPressed = ...  # type: QtGui.QColor
    primaryColorTransparent = ...  # type: QtGui.QColor
    progressBarGrooveHeight = ...  # type: int
    scrollBarMargin = ...  # type: int
    scrollBarThicknessFull = ...  # type: int
    scrollBarThicknessSmall = ...  # type: int
    secondaryAlternativeColor = ...  # type: QtGui.QColor
    secondaryAlternativeColorDisabled = ...  # type: QtGui.QColor
    secondaryAlternativeColorHovered = ...  # type: QtGui.QColor
    secondaryAlternativeColorPressed = ...  # type: QtGui.QColor
    secondaryAlternativeColorTransparent = ...  # type: QtGui.QColor
    secondaryColor = ...  # type: QtGui.QColor
    secondaryColorDisabled = ...  # type: QtGui.QColor
    secondaryColorForeground = ...  # type: QtGui.QColor
    secondaryColorForegroundDisabled = ...  # type: QtGui.QColor
    secondaryColorForegroundHovered = ...  # type: QtGui.QColor
    secondaryColorForegroundPressed = ...  # type: QtGui.QColor
    secondaryColorForegroundTransparent = ...  # type: QtGui.QColor
    secondaryColorHovered = ...  # type: QtGui.QColor
    secondaryColorPressed = ...  # type: QtGui.QColor
    secondaryColorTransparent = ...  # type: QtGui.QColor
    semiTransparentColor1 = ...  # type: QtGui.QColor
    semiTransparentColor2 = ...  # type: QtGui.QColor
    semiTransparentColor3 = ...  # type: QtGui.QColor
    semiTransparentColor4 = ...  # type: QtGui.QColor
    semiTransparentColorTransparent = ...  # type: QtGui.QColor
    shadowColor1 = ...  # type: QtGui.QColor
    shadowColor2 = ...  # type: QtGui.QColor
    shadowColor3 = ...  # type: QtGui.QColor
    shadowColorTransparent = ...  # type: QtGui.QColor
    sliderAnimationDuration = ...  # type: int
    sliderGrooveHeight = ...  # type: int
    sliderTickSize = ...  # type: int
    sliderTickSpacing = ...  # type: int
    sliderTickThickness = ...  # type: int
    spacing = ...  # type: int
    statusColorError = ...  # type: QtGui.QColor
    statusColorErrorDisabled = ...  # type: QtGui.QColor
    statusColorErrorHovered = ...  # type: QtGui.QColor
    statusColorErrorPressed = ...  # type: QtGui.QColor
    statusColorForeground = ...  # type: QtGui.QColor
    statusColorForegroundDisabled = ...  # type: QtGui.QColor
    statusColorForegroundHovered = ...  # type: QtGui.QColor
    statusColorForegroundPressed = ...  # type: QtGui.QColor
    statusColorInfo = ...  # type: QtGui.QColor
    statusColorInfoDisabled = ...  # type: QtGui.QColor
    statusColorInfoHovered = ...  # type: QtGui.QColor
    statusColorInfoPressed = ...  # type: QtGui.QColor
    statusColorSuccess = ...  # type: QtGui.QColor
    statusColorSuccessDisabled = ...  # type: QtGui.QColor
    statusColorSuccessHovered = ...  # type: QtGui.QColor
    statusColorSuccessPressed = ...  # type: QtGui.QColor
    statusColorWarning = ...  # type: QtGui.QColor
    statusColorWarningDisabled = ...  # type: QtGui.QColor
    statusColorWarningHovered = ...  # type: QtGui.QColor
    statusColorWarningPressed = ...  # type: QtGui.QColor
    tabBarPaddingTop = ...  # type: int
    tabBarTabMaxWidth = ...  # type: int
    tabBarTabMinWidth = ...  # type: int
    useSystemFonts = ...  # type: bool

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, other: Theme, /) -> None: ...
    def __copy__(self, /) -> Self: ...
    def __eq__(self, other: Theme, /) -> bool: ...
    def __ne__(self, other: Theme, /) -> bool: ...
    @staticmethod
    def fromJsonDoc(jsonDoc: QtCore.QJsonDocument, /) -> Theme: ...
    @staticmethod
    def fromJsonPath(jsonPath: str, /) -> Theme: ...
    def toJson(self, /) -> QtCore.QJsonDocument: ...

class ThemeManager(QtCore.QObject):
    @typing.overload
    def __init__(
        self,
        style: QlementineStyle,
        /,
        parent: QtCore.QObject | None = ...,
        *,
        currentTheme: str | None = ...,
        themeCount: int | None = ...,
    ) -> None: ...
    @typing.overload
    def __init__(
        self,
        /,
        parent: QtCore.QObject | None = ...,
        *,
        currentTheme: str | None = ...,
        themeCount: int | None = ...,
    ) -> None: ...
    def addTheme(self, theme: Theme, /) -> None: ...
    def currentTheme(self, /) -> str: ...
    def currentThemeChanged(self, /) -> None: ...
    def currentThemeIndex(self, /) -> int: ...
    def loadDirectory(self, path: str, /) -> None: ...
    def setCurrentTheme(self, key: str, /) -> None: ...
    def setCurrentThemeIndex(self, index: int, /) -> None: ...
    def setNextTheme(self, /) -> None: ...
    def setPreviousTheme(self, /) -> None: ...
    def setStyle(self, style: QlementineStyle, /) -> None: ...
    def style(self, /) -> QlementineStyle: ...
    def themeCount(self, /) -> int: ...
    def themeCountChanged(self, /) -> None: ...
    def themeIndex(self, key: str, /) -> int: ...
    def themes(self, /) -> list[Theme]: ...

class ThemeMeta:
    author = ...  # type: str
    name = ...  # type: str
    version = ...  # type: str

    @typing.overload
    def __init__(self, /) -> None: ...
    @typing.overload
    def __init__(self, ThemeMeta: ThemeMeta, /) -> None: ...
    def __copy__(self, /) -> Self: ...
    def __eq__(self, other: ThemeMeta, /) -> bool: ...
    def __ne__(self, other: ThemeMeta, /) -> bool: ...

def blurRadiusNecessarySpace(blurRadius: float, /) -> int: ...
def colorizeImage(
    input: QtGui.QPixmap | QtGui.QImage,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    /,
) -> QtGui.QImage: ...
def colorizePixmap(
    input: QtGui.QPixmap | QtGui.QImage,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    /,
) -> QtGui.QPixmap: ...
def drawStatusBadge(
    p: QtGui.QPainter,
    rect: QtCore.QRect,
    statusBadge: StatusBadge,
    size: StatusBadgeSize,
    theme: Theme,
    /,
) -> None: ...
def getBlurredPixmap(
    input: QtGui.QPixmap | QtGui.QImage, blurRadius: float, /
) -> QtGui.QPixmap: ...
def getCachedPixmap(
    input: QtGui.QPixmap | QtGui.QImage,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    mode: ColorizeMode,
    /,
) -> QtGui.QPixmap: ...
def getColorizedPixmap(
    input: QtGui.QPixmap | QtGui.QImage,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    /,
) -> QtGui.QPixmap: ...
def getColorizedPixmapKey(
    pixmap: QtGui.QPixmap | QtGui.QImage,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    /,
) -> str: ...
@typing.overload
def getDropShadowPixmap(
    size: QtCore.QSize,
    borderRadius: float,
    blurRadius: float,
    /,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int = ...,
) -> QtGui.QPixmap: ...
@typing.overload
def getDropShadowPixmap(
    input: QtGui.QPixmap | QtGui.QImage,
    blurRadius: float,
    /,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int = ...,
) -> QtGui.QPixmap: ...
@typing.overload
def getExtendedImage(input: QtGui.QImage, padding: int, /) -> QtGui.QImage: ...
@typing.overload
def getExtendedImage(
    input: QtGui.QPixmap | QtGui.QImage, padding: int, /
) -> QtGui.QImage: ...
def getImageAspectRatio(path: str, /) -> float: ...
def getStatusBadgeSizes(
    statusBadgeSize: StatusBadgeSize, theme: Theme, /
) -> tuple[QtCore.QSize, QtCore.QSize]: ...
def getTintedPixmap(
    input: QtGui.QPixmap | QtGui.QImage,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    /,
) -> QtGui.QPixmap: ...
def getTintedPixmapKey(
    pixmap: QtGui.QPixmap | QtGui.QImage,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    /,
) -> str: ...
def makeFitPixmap(
    input: QtGui.QPixmap | QtGui.QImage, size: QtCore.QSize, /
) -> QtGui.QPixmap: ...
def makeIconFromSvg(svgPath: str, size: QtCore.QSize, /) -> QtGui.QIcon: ...
@typing.overload
def makePixmapFromSvg(svgPath: str, size: QtCore.QSize, /) -> QtGui.QPixmap: ...
@typing.overload
def makePixmapFromSvg(
    backgroundSvgPath: str,
    backgroundSvgColor: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    foregroundSvgPath: str,
    foregroundSvgColor: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    size: QtCore.QSize,
    /,
) -> QtGui.QPixmap: ...
@typing.overload
def makeRoundedPixmap(
    input: QtGui.QPixmap | QtGui.QImage, radiuses: RadiusesF, /
) -> QtGui.QPixmap: ...
@typing.overload
def makeRoundedPixmap(
    input: QtGui.QPixmap | QtGui.QImage, radius: float, /
) -> QtGui.QPixmap: ...
@typing.overload
def makeRoundedPixmap(
    input: QtGui.QPixmap | QtGui.QImage,
    topLeft: float,
    topRight: float,
    bottomRight: float,
    bottomLeft: float,
    /,
) -> QtGui.QPixmap: ...
def tintPixmap(
    input: QtGui.QPixmap | QtGui.QImage,
    color: QtGui.QColor
    | str
    | QtGui.QRgba64
    | typing.Any
    | QtCore.Qt.GlobalColor
    | int,
    /,
) -> QtGui.QPixmap: ...

# eof
